"""Public simulation facade over problems, methods, integration and results."""

from formulations.state import PhysicalFormulation, DoubledFormulation
from contracts.configuration import InitialConfiguration, StateLayout
from formulations import (
	DirectAdjointFormulation,
	FCSplitFormulation,
	GCExtendedFormulation,
	GCStageProjectedFormulation,
	StageProjectedFormulation,
	gc_coupling_matrix,
)
from methods import (
	DOP853,
	Radau,
	ABBA2Midpoint,
	ABBA2Implicit,
	ABBA4Implicit,
	ABBA6Implicit,
	ABBA4_PROJECTION_PLACEMENTS,
	BM4Implicit,
	BM4Midpoint,
	ExplicitEuler,
	GAUSS_JACOBIAN_METHODS,
	GaussJacobianMethod,
	GaussLegendre4,
	HBVM42,
	HBVMJacobianMethod,
	ABBA_PROJECTION_FORMULATIONS,
	ABBA_STATE_EXTENSIONS,
	NONLINEAR_SOLVERS,
	NonlinearSolver,
	NumericalMethod,
	ProjectionPlacement,
	ProjectionFormulation,
	StateExtension,
	RK4,
	SDIRK4_TABLEAU_A,
	SDIRK4_TABLEAU_B,
	SDIRK4_TABLEAU_C,
	SDIRK_JACOBIAN_METHODS,
	SDIRK4,
	SDIRKJacobianMethod,
)
from contracts.observation import AdaptiveIntegrationStep, AdaptiveStepObserver, ABBA4ImplicitIntegrationStep, GaussLegendre4IntegrationStep, ABBA6ImplicitIntegrationStep, ABBAImplicitCompositionIntegrationStep, ABBA2ImplicitIntegrationStep, ImplicitBM4IntegrationStep, ImplicitIntegrationStep, IntegrationStage, IntegrationStep, StageObserver, StepObserver, UnprojectedABBAIntegrationStep
from contracts.problem import InitialValueProblem
from contracts.request import (
	DEFAULT_INTEGRATION_STEP,
	DEFAULT_INTEGRATION_STEPS_PER_CYCLE,
	DEFAULT_SAVED_STEPS_PER_CYCLE,
	DEFAULT_SAVE_INTERVAL,
	NORMALIZED_CYCLE_DURATION,
	SimulationRequest,
)
from .runner import (
	simulate,
)
from solution import Solution

__all__ = [
	"PhysicalFormulation",
	"DoubledFormulation",
	"DOP853",
	"Radau",
	"AdaptiveIntegrationStep",
	"AdaptiveStepObserver",
	"ABBA2Midpoint",
	"ABBA2Implicit",
	"ABBA4Implicit",
	"ABBA4ImplicitIntegrationStep",
	"ABBA6Implicit",
	"BM4Implicit",
	"BM4Midpoint",
	"ExplicitEuler",
	"GAUSS_JACOBIAN_METHODS",
	"GaussJacobianMethod",
	"GaussLegendre4",
	"HBVM42",
	"HBVMJacobianMethod",
	"DirectAdjointFormulation",
	"DEFAULT_INTEGRATION_STEP",
	"DEFAULT_INTEGRATION_STEPS_PER_CYCLE",
	"DEFAULT_SAVED_STEPS_PER_CYCLE",
	"DEFAULT_SAVE_INTERVAL",
	"ABBA4_PROJECTION_PLACEMENTS",
	"ABBA_PROJECTION_FORMULATIONS",
	"ABBA_STATE_EXTENSIONS",
	"FCSplitFormulation",
	"GCExtendedFormulation",
	"GCStageProjectedFormulation",
	"gc_coupling_matrix",
	"InitialConfiguration",
	"GaussLegendre4IntegrationStep",
	"InitialValueProblem",
	"ABBA6ImplicitIntegrationStep",
	"ABBAImplicitCompositionIntegrationStep",
	"ABBA2ImplicitIntegrationStep",
	"ImplicitBM4IntegrationStep",
	"ImplicitIntegrationStep",
	"IntegrationStage",
	"IntegrationStep",
	"NONLINEAR_SOLVERS",
	"NORMALIZED_CYCLE_DURATION",
	"NonlinearSolver",
	"NumericalMethod",
	"ProjectionPlacement",
	"ProjectionFormulation",
	"StateExtension",
	"RK4",
	"SDIRK4_TABLEAU_A",
	"SDIRK4_TABLEAU_B",
	"SDIRK4_TABLEAU_C",
	"SDIRK_JACOBIAN_METHODS",
	"SDIRK4",
	"SDIRKJacobianMethod",
	"SimulationRequest",
	"Solution",
	"StageObserver",
	"StepObserver",
	"StageProjectedFormulation",
	"StateLayout",
	"UnprojectedABBAIntegrationStep",
	"simulate",
]
