"""Opt-in diagnostics built around the stable simulation core."""

from .abba_jacobian import (
	IMPLICIT_ABBA_JACOBIAN_METHODS,
	ImplicitABBAJacobianMethod,
	ImplicitABBAJacobianObserver,
	ImplicitABBAJacobianOutputBlock,
	ImplicitABBAJacobianRecord,
	ImplicitABBAJacobianSample,
	ParticleJacobianAnalysis,
	SpectralClass,
	analyze_particle_jacobian,
)
from .abba_reversibility import (
	ImplicitABBAReversibilityObserver,
	ImplicitABBAReversibilitySample,
)
from .bm4_midpoint import (
	MIDPOINT_BM4_STAGE_COUNT,
	MidpointBM4SymplecticityObserver,
	MidpointBM4SymplecticityOutputBlock,
	MidpointBM4SymplecticityRecord,
	midpoint_bm4_stage_particle_jacobians,
	midpoint_bm4_step_particle_jacobians,
)
from .jacobians import (
	STEP_JACOBIAN_METHODS,
	StepJacobianMethod,
	calculate_step_jacobian,
	central_difference_jacobian,
	implicit_function_step_jacobian,
	stage_increment_step_jacobian,
)
from .trajectory_symplecticity import (
	abba4_implicit_1_step_particle_jacobians,
	GCTrajectorySymplecticityObserver,
	TrajectoryJacobianCalculator,
	TrajectorySymplecticityOutputBlock,
	TrajectorySymplecticityRecord,
	bm4_implicit_1_step_particle_jacobians,
	coupled_bm4_stage_particle_jacobians,
	implicit_abba_1_step_particle_jacobians,
	midpoint_abba_step_particle_jacobians,
)
from .implicit_iterations import (
	ImplicitABBAIterationObserver,
	ImplicitABBAIterationOutputBlock,
	ImplicitABBAIterationRecord,
	ImplicitBM4IterationObserver,
	ImplicitBM4IterationOutputBlock,
	ImplicitBM4IterationRecord,
	ImplicitIterationOutputBlock,
	ImplicitIterationRecord,
)
from .reference_trajectory import (
	ReferenceTrajectoryPaths,
	StoredReferenceTrajectory,
	load_reference_trajectory,
	reference_trajectory_output_directory,
	write_reference_trajectory,
)

__all__ = [
	"abba4_implicit_1_step_particle_jacobians",
	"IMPLICIT_ABBA_JACOBIAN_METHODS",
	"ImplicitABBAJacobianMethod",
	"ImplicitABBAJacobianObserver",
	"ImplicitABBAJacobianOutputBlock",
	"ImplicitABBAJacobianRecord",
	"ImplicitABBAJacobianSample",
	"ImplicitABBAReversibilityObserver",
	"ImplicitABBAReversibilitySample",
	"ImplicitABBAIterationObserver",
	"ImplicitABBAIterationOutputBlock",
	"ImplicitABBAIterationRecord",
	"ImplicitBM4IterationObserver",
	"ImplicitBM4IterationOutputBlock",
	"ImplicitBM4IterationRecord",
	"ImplicitIterationOutputBlock",
	"ImplicitIterationRecord",
	"GCTrajectorySymplecticityObserver",
	"MIDPOINT_BM4_STAGE_COUNT",
	"MidpointBM4SymplecticityObserver",
	"MidpointBM4SymplecticityOutputBlock",
	"MidpointBM4SymplecticityRecord",
	"ParticleJacobianAnalysis",
	"ReferenceTrajectoryPaths",
	"STEP_JACOBIAN_METHODS",
	"SpectralClass",
	"TrajectoryJacobianCalculator",
	"TrajectorySymplecticityOutputBlock",
	"TrajectorySymplecticityRecord",
	"StepJacobianMethod",
	"StoredReferenceTrajectory",
	"analyze_particle_jacobian",
	"calculate_step_jacobian",
	"bm4_implicit_1_step_particle_jacobians",
	"central_difference_jacobian",
	"coupled_bm4_stage_particle_jacobians",
	"implicit_abba_1_step_particle_jacobians",
	"implicit_function_step_jacobian",
	"load_reference_trajectory",
	"midpoint_bm4_stage_particle_jacobians",
	"midpoint_bm4_step_particle_jacobians",
	"midpoint_abba_step_particle_jacobians",
	"reference_trajectory_output_directory",
	"stage_increment_step_jacobian",
	"write_reference_trajectory",
]
