"""Optional Matplotlib presentation for potentials and simulation results."""

from .abba4_configuration_comparison import (
	animate_abba4_configuration_trajectories,
)
from .abba4_projection_comparison import (
	ABBA4_PROJECTION_COLORS,
	ABBA4ProjectionOrderView,
	ABBA4ProjectionSummaryView,
	plot_abba4_projection_accuracy,
	plot_abba4_projection_multiplier_scaling,
	plot_abba4_projection_newton_work,
	plot_abba4_projection_order_reduction,
	plot_abba4_projection_runtime,
)
from .abba_jacobian import (
	plot_implicit_abba_particle_step_series,
	plot_implicit_abba_jacobian_directions,
	plot_implicit_abba_jacobian_matrices,
	plot_implicit_abba_jacobian_polar_snapshots,
	plot_implicit_abba_jacobian_spectrum,
)
from .abba_reversibility import (
	plot_implicit_abba_reversibility_diagnostics,
	plot_implicit_abba_transport_components,
)
from .bm4_midpoint_symplecticity import (
	plot_midpoint_bm4_symplecticity,
	plot_midpoint_bm4_trajectories,
)
from .gc_area import (
	animate_gc_area,
	animate_gc_area_comparison,
	animate_gc_area_solution,
)
from .implicit_iterations import (
	plot_implicit_abba_iteration_comparison,
	plot_implicit_abba_iteration_diagnostics,
	plot_implicit_bm4_iteration_comparison,
	plot_implicit_bm4_iteration_diagnostics,
	plot_implicit_iteration_comparison,
	plot_implicit_iteration_diagnostics,
)
from .implicit_comparison import (
	IMPLICIT_METHOD_COLORS,
	animate_implicit_method_trajectories,
	plot_implicit_method_iterations,
	plot_implicit_trajectory_differences,
)
from .implicit_method_accuracy import (
	IMPLICIT_ACCURACY_COLORS,
	ImplicitMethodAccuracyOrderView,
	ImplicitMethodAccuracySummaryView,
	plot_implicit_method_accuracy_cost,
	plot_implicit_method_accuracy_refinement,
	plot_implicit_method_newton_refinement,
	plot_implicit_method_observed_orders,
)
from .energy import (
	EnergyAccuracySeriesView,
	ExtendedSymplecticityRunView,
	ReducedExtendedSymplecticityRunView,
	GeneralizedEnergyRunView,
	GeneralizedEnergySummaryView,
	plot_generalized_energy_components,
	plot_generalized_energy_convergence,
	plot_generalized_energy_errors,
	plot_energy_accuracy_over_time,
	plot_time_extended_symplecticity,
	plot_reduced_time_extended_symplecticity,
)
from .fully_extended_implicit import (
	FullyExtendedRunView,
	plot_fully_extended_symplecticity,
)
from .hbvm42 import (
	HBVM42BM4SummaryView,
	HBVM42EvaluationSummaryView,
	HBVM42OrderSummaryView,
	plot_hbvm42_bm4_comparison,
	plot_hbvm42_energy_errors,
	plot_hbvm42_evaluation,
)
from .notebooks import display_animation, display_records_table, records_table_html
from .particles import (
	animate_fc_particle_solution,
	animate_gc_particle_solution,
	animate_gc_particle_trajectories,
)
from .potential import animate_potential, plot_potential
from .projected_bm4_symplecticity import (
	plot_projected_bm4_symplecticity_convergence,
	plot_projected_bm4_symplecticity_diagnostics,
)
from .trajectory_symplecticity import (
	TrajectorySymplecticityRecordView,
	plot_gc_trajectory_points,
	plot_trajectory_symplecticity,
)
from .ten_method_comparison import (
	TEN_METHOD_COLORS,
	TEN_METHOD_SHORT_LABELS,
	animate_ten_method_trajectory_points,
	animate_trajectory_points,
	plot_ten_method_nonlinear_work,
	plot_ten_method_runtimes,
	plot_ten_method_trajectory_differences,
)
from .trajectory_accuracy import (
	AccuracySeriesView,
	AccuracySummaryView,
	StepAccuracySummaryView,
	plot_accuracy_summary,
	plot_accuracy_runtime_tradeoff,
	plot_reference_trajectory_points,
	plot_single_method_accuracy_refinement,
	plot_ten_method_accuracy_over_time,
	plot_ten_method_accuracy_refinement,
	plot_ten_method_accuracy_summary,
	plot_trajectory_accuracy_over_time,
)
from .gauss_legendre4 import (
	GAUSS_BM4_COLORS,
	plot_gauss_bm4_accuracy_runtime,
	plot_gauss_legendre4_evaluation,
	plot_gauss_legendre4_energy,
	plot_gauss_legendre4_observed_order,
	plot_gauss_legendre4_symplecticity,
)

__all__ = [
	"GAUSS_BM4_COLORS",
	"AccuracySeriesView",
	"AccuracySummaryView",
	"ABBA4_PROJECTION_COLORS",
	"ABBA4ProjectionOrderView",
	"ABBA4ProjectionSummaryView",
	"StepAccuracySummaryView",
	"animate_abba4_configuration_trajectories",
	"animate_fc_particle_solution",
	"animate_gc_area",
	"animate_gc_area_comparison",
	"animate_gc_area_solution",
	"animate_gc_particle_solution",
	"animate_gc_particle_trajectories",
	"animate_implicit_method_trajectories",
	"animate_potential",
	"animate_ten_method_trajectory_points",
	"animate_trajectory_points",
	"display_animation",
	"display_records_table",
	"IMPLICIT_METHOD_COLORS",
	"IMPLICIT_ACCURACY_COLORS",
	"ImplicitMethodAccuracyOrderView",
	"ImplicitMethodAccuracySummaryView",
	"GeneralizedEnergyRunView",
	"GeneralizedEnergySummaryView",
	"EnergyAccuracySeriesView",
	"HBVM42BM4SummaryView",
	"HBVM42EvaluationSummaryView",
	"HBVM42OrderSummaryView",
	"FullyExtendedRunView",
	"ExtendedSymplecticityRunView",
	"ReducedExtendedSymplecticityRunView",
	"TEN_METHOD_COLORS",
	"TEN_METHOD_SHORT_LABELS",
	"plot_implicit_abba_jacobian_directions",
	"plot_implicit_abba_iteration_diagnostics",
	"plot_implicit_abba_iteration_comparison",
	"plot_implicit_bm4_iteration_comparison",
	"plot_implicit_bm4_iteration_diagnostics",
	"plot_implicit_iteration_comparison",
	"plot_implicit_iteration_diagnostics",
	"plot_implicit_method_iterations",
	"plot_implicit_method_accuracy_cost",
	"plot_implicit_method_accuracy_refinement",
	"plot_implicit_method_newton_refinement",
	"plot_implicit_method_observed_orders",
	"plot_implicit_trajectory_differences",
	"plot_implicit_abba_jacobian_matrices",
	"plot_implicit_abba_jacobian_polar_snapshots",
	"plot_implicit_abba_jacobian_spectrum",
	"plot_implicit_abba_reversibility_diagnostics",
	"plot_implicit_abba_transport_components",
	"plot_implicit_abba_particle_step_series",
	"plot_gc_trajectory_points",
	"plot_generalized_energy_components",
	"plot_generalized_energy_convergence",
	"plot_generalized_energy_errors",
	"plot_energy_accuracy_over_time",
	"plot_gauss_bm4_accuracy_runtime",
	"plot_gauss_legendre4_evaluation",
	"plot_gauss_legendre4_energy",
	"plot_gauss_legendre4_observed_order",
	"plot_gauss_legendre4_symplecticity",
	"plot_hbvm42_bm4_comparison",
	"plot_hbvm42_energy_errors",
	"plot_hbvm42_evaluation",
	"plot_fully_extended_symplecticity",
	"plot_time_extended_symplecticity",
	"plot_reduced_time_extended_symplecticity",
	"plot_accuracy_summary",
	"plot_accuracy_runtime_tradeoff",
	"plot_abba4_projection_accuracy",
	"plot_abba4_projection_multiplier_scaling",
	"plot_abba4_projection_newton_work",
	"plot_abba4_projection_order_reduction",
	"plot_abba4_projection_runtime",
	"plot_midpoint_bm4_symplecticity",
	"plot_midpoint_bm4_trajectories",
	"plot_potential",
	"plot_projected_bm4_symplecticity_convergence",
	"plot_projected_bm4_symplecticity_diagnostics",
	"plot_reference_trajectory_points",
	"plot_single_method_accuracy_refinement",
	"plot_trajectory_symplecticity",
	"plot_ten_method_nonlinear_work",
	"plot_ten_method_accuracy_over_time",
	"plot_ten_method_accuracy_refinement",
	"plot_ten_method_accuracy_summary",
	"plot_trajectory_accuracy_over_time",
	"plot_ten_method_runtimes",
	"plot_ten_method_trajectory_differences",
	"records_table_html",
	"TrajectorySymplecticityRecordView",
]
