CONFIG = {'schema_version': 1,
 'active_version': 'default',
 'versions': {'default': {'parallelization': 1,
                          'pyhamsys': {'TimeStep': 0.1, 'ode_solver': 'BM4', 'CheckEnergy': False},
                          'defaults': {'Method': 'poincare_gc',
                                       'Ntraj': 50,
                                       'Tf': 500,
                                       'TwoStepIntegration': True,
                                       'Tmid': 200,
                                       'threshold': 4,
                                       'thresh_b': 1.2,
                                       'init': 'selected',
                                       'x0': {'linspace': [0.5, 1.0, 'Ntraj']},
                                       'y0': {'constant': 4.5, 'num': 'Ntraj'},
                                       'PlotResults': True,
                                       'modulo': True,
                                       'grid': False,
                                       'darkmode': True,
                                       'extension': '.pdf',
                                       'dpi': 200,
                                       'SaveData': False,
                                       'M': 25},
                          'sweep': {'A': [0.7], 'rho': [0.1]}},
              'symplectic_grid': {'parallelization': 2,
                                  'pyhamsys': {'TimeStep': 0.1,
                                               'ode_solver': 'BM4',
                                               'CheckEnergy': True},
                                  'defaults': {'Method': 'poincare_gc',
                                               'traj_type': 'gc',
                                               'Ntraj': 5,
                                               'Tf': 50,
                                               'init': 'fixed',
                                               'SaveData': False,
                                               'M': 25},
                                  'sweep': {'A': [0.7], 'rho': [0.1, 0.3], 'eta': [-0.2, 0.3]}}}}
